version: '2.1'

services:
  master:
    image: 'citus-local'
    container_name: 'citus_master'
    build:
      context: .
    labels:
      - 'com.citusdata.role=Master'
    volumes:
      - './data:/tmp/data'
    ports:
      - '5432:5432'

  manager:
    image: 'citusdata/membership-manager:0.2.0'
    container_name: 'citus_manager'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on: { master: { condition: service_healthy } }

  worker:
    image: 'citus-local'
    labels:
      - 'com.citusdata.role=Worker'
    depends_on: { manager: { condition: service_healthy } }
